### PR TITLE
4.0.1: Update dependencies and Actions

### PR DESCRIPTION
**Pull request by wp99cp**
- [x] bump version number (new: 4.0.1)
- [x] get actions running

### CODE REVIEW

**Comment by maede97** [comment]
Currently the action fails with: 
however, the line in `package.json` (`"@types/ws": "^8.5.4",`) should fix this. I am not sure why it does not work...

**Comment by wp99cp** [comment]
> Currently, the action fails with: `node_modules/@types/ws/index.d.ts(321,18): error TS2315: Type 'Server' is not generic.` however, the line in `package.json` (`"@types/ws": "^8.5.4",`) should fix this. I am not sure why it does not work...

Changing `package.json` by itself does not change the version of the used package (which is rather defined in `package-lock.json`). For that, you have to run `npm i` after the change. This will resolve all package dependencies, solve for conflicts and update the package-lock.json` file. This file is then used inside the docker container.

**Comment by maede97** [comment]
Mhhh I did. Maybe I missed something. Let's see if it works now :-)

**Comment by wp99cp** [comment]
@maede97, you can merge this PR with the current state.
I tried to upgrade the angular version, but this introduces some breaking changes to the UI (e.g. the button colors are missing). We should address that separately...

image

**Review by maede97 — APPROVED** [review]

**Pull request merged**
