### PR TITLE
Fix route-name missing 

### PR DESCRIPTION
**Pull request by maede97**
This PR tracks our work in fixing #136 

As far as I can tell, the route name gets extracted correctly. However, the webinterface interacts with JSON with the backend.
In the webinterface call to /create-walk-time-table does however not include the route_name.
The fix in the backend is already present backend/app/app.py:152 and should be added once the webinterface is fixed.

- [x] Fix webinterface
- [x] Fix app.py:152

### CODE REVIEW

**Comment by wp99cp** [comment]
Should we fix #144 as well?

**Comment by wp99cp** [comment]
TODO:
- [ ] For KML files we get an error:
`[ERROR] Exception while parsing file: local variable 'route_name' referenced before assignment`

**Comment by maede97** [comment]
It is better, but still wrong. Now, the frontend returns the full filename, not the route_name.

**Comment by wp99cp** [comment]
> It is better, but still wrong. Now, the frontend returns the full filename, not the route_name.

Implemented with f14d4588d1035633b2895e62e232d04581566f08

**Comment by maede97** [comment]
Looks good to me!

**Pull request merged**
