### PR TITLE
6.1.0 - Storing Improvements

### PR DESCRIPTION
**Pull request by maede97**
- [x] Importing Swisstopo GPX file should restore way_points in our app -> moved to #539 
- [x] Names of Waypoint are not stored in the database but regenerated on-the-fly for each export 0dd79568686db562cd413e14ed45b37fecce4ea8
- [x] call to retrieve should clear log (currently, shows old log from server) c76890e5d7c69daf04cd43d150259a6d18c45c6c
- [x] Add QR code to frontend after first download https://github.com/cevi/automatic_walk-time_tables/commit/358c51ddc411b83ab6a6a069d88e6d4e13f7ba93
- [x] Add link to share for retrieve after first download on webpage 1944d1a8aa064052769123ee4fabf0607a891861
- [x] ZIP download should contain generated GPX file a96fc0ab324355ca4d4bc1febcc0c072f9b57904
- [x] @wp99cp add 814.json to dev deployment
- [x] @wp99cp add 814.json to deployment
- [x] @wp99cp remove cached name index for dev deployment (and restart swiss-tml-api container
- [x] fix swiss tml names not stored in the excel file

### CODE REVIEW

**Comment by maede97** [comment]
@wp99cp 
What do you mean by this:
- [ ] Names of Waypoint are not included in Swisstopo Export as they are not saved in the DB
For me, the waypoints do have a name in the swisstopo app

**Comment by wp99cp** [comment]
> @wp99cp 
> What do you mean by this:
> - [ ] Names of Waypoint are not included in Swisstopo Export as they are not saved in the DB
> For me, the waypoints do have a name in the swisstopo app

I think currently they are regenerated on the fly for every GPX download but you are correct they are included in the GPX.
However, we should save them in the DB in order to be future proof and allow for persistent custom names.

**Comment by maede97** [comment]
@wp99cp 
> Names of Waypoint are not stored in the database but regenerated on-the-fly for each export

I am not sure if we actually want this. If we improve naming later, we can create better point names in future exports?
I propose a wontfix for this.

**Comment by wp99cp** [comment]
> * fix swiss tml names not stored in the excel file

I deleted the index once again, now I can no longer reproduce the issue:

image

**Comment by maede97** [comment]
Also map numbers semm to work now as well :-)

**Comment by maede97** [comment]
image

**Comment by wp99cp** [comment]
A retriggered export duplicates the coordinates in the excel export
image

**Review by wp99cp — APPROVED** [review]

**Pull request merged**
