### PR TITLE
[5.1.0] Remove Height profile

### PR DESCRIPTION
**Pull request by maede97**
Content of this PR:
- remove of height profile
- cleanup of AutomatedWalkTableGenerator class
- always generate excel and pdf

With this PR, the height profile support is dropped.
the user can no longer select whether to generate excel or pdf, both are generated.

### CODE REVIEW

**Review by wp99cp — APPROVED** [review]

**Comment by carlobeltrame** [comment]
Why was the elevation profile removed? I thought it was quite useful, way more useful than the graph in the excel file. It was also a good teaching tool, because it visualized the difference between the real elevation profile and the calculated one from the Marschzeittabelle.
Switzerland mobility also provides support for downloading the elevation profile as SVG, but not everyone has an account there. And if you still plan on allowing to draw routes directly in the cevi tool, this option would be missing now.

**Comment by maede97** [comment]
We will add it back! :-)
We did not think that it was used but your points definitively make sense!

**Comment by maede97** [comment]
It is added again in the WIP of version 6.0. so it will come back probably in a few weeks.

**Comment by carlobeltrame** [comment]
Thanks a lot for taking my feedback seriously!

**Pull request merged**
