### PR TITLE
Minor Update: Circular Paths & updates

### PR DESCRIPTION
**Pull request by maede97**
- Circular Paths in KML are now supported
- Dependencies updated
- Readme updates

### CODE REVIEW

**Review by wp99cp — CHANGES_REQUESTED** [review]
Dev Deployment crashes with the backend container reporting: 

```bash
Exception in thread Thread-2 (create_export):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app.py", line 210, in create_export
    options['print-api-base-url'] = os.environ['PRINT_API_BASE_URL']
                                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'PRINT_API_BASE_URL'
```

**Comment by maede97** [comment]
@wp99cp has the deployment a different env file?

**Comment by maede97** [comment]
For me locally, the ENV file is successfully loaded and works as intended...

**Comment by wp99cp** [comment]
The hosted version has both the dev and prod instances and no environment files configured.
It seems that they aren't needed until now?

I will update the deployment process and add the environment variable. Will update you as soon as that is done (it will take some time...)

**Comment by maede97** [comment]
> I will update the deployment process and add the environment variable. Will update you as soon as that is done (it will take some time...)

Any update on this?

**Review by wp99cp — DISMISSED** [review]

**Pull request merged**
