### PR TITLE
Use a more robust IF check in the excel formulas

### LINKED ISSUE #409: Berechnung in der Tabelle falsch wenn eine sehr kurze Teilstrecke auf 0 Minuten abgerundet wird
Manchmal kommt es vor, dass der Punktefindungs-Algorithmus zwei Punkte wählt die extrem nahe beieinander sind. Beispiel in dieser generierten Tabelle:
[Hinweg Sola 24_Marschzeittabelle.xlsx](https://github.com/user-attachments/files/16029977/Hinweg.Sola.24_Marschzeittabelle.xlsx)
Leider habe ich die original verwendete GPS-Route nicht, aber die Wanderung ist von Steg im Tösstal zu einem nahen Lagerplatz.

Die Zeilen 16 und 17 sind effektiv praktisch derselbe geografische Ort, aber einmal mit 732 m.ü.M. und einmal mit 735 m.ü.M.
Dies führt zu einer Horizontaldistanz von 0, abgerundeten 0 Lkm, und einer Zeitdauer von 0:00. Das wiederum hat diverse Folgen in den Gesamtsummen-Formeln, wo ab dieser Zeile falsche Angaben berechnet werden.

Natürlich wäre es auch schön, wenn der Punktewahl-Algorithmus diese Punkte gar nicht erst wählen würde. Jedoch ist diese Situation mit manueller Punktewahl vermutlich immer möglich. Daher fände ich es wichtig, dass die Formeln in der Excel-Vorlage damit umgehen können wenn eine fast leere Teilstrecke eingefügt wird.

### PR DESCRIPTION
**Pull request by carlobeltrame**
Fixes #409
In the formulas in columns D, F and G, the `IF` conditions are changed from `E9=0` to `A9=""`, to be able to handle very short segments where the horizontal distance rounds down to 0.
In the formulas in column K, the `IF` condition is removed entirely, because this condition isn't required for the correct behaviour, and it caused the planned time of arrival to be reset to zero in edge cases.

### CODE REVIEW

**Comment by wp99cp** [comment]
Thanks for your contribution.
In general your solution looks good, however you also introduce a new bug with our solution.

In the edge case where the horizontal distance is set to zero, the sum of the Lkm ("Summe Leistungskilometer") does no longer work with your changes applies, see the following example:
image

how it looks without your changes:
image


@carlobeltrame can you confirm that using Excel (I tested it using LibreOffice)?

**Review by wp99cp — CHANGES_REQUESTED** [review]
Thanks for your contribution.
In general your solution looks good, however you also introduce a new bug with our solution.

In the edge case where the horizontal distance is set to zero, the sum of the Lkm ("Summe Leistungskilometer") does no longer work with your changes applies, see the following example:
image

how it looks without your changes:
image


@carlobeltrame can you confirm that using Excel (I tested it using LibreOffice)?

**Comment by carlobeltrame** [comment]
> Thanks for your contribution. In general your solution looks good, however you also introduce a new bug with our solution.

I think your testing setup is flawed. Your first column (point names) is completely empty, and my proposed formulas rely on them being filled in. As far as I can tell, the backend of this project will always fill this column in with something (please let me know if that is not the case), that is why I changed the `IF` conditions to look for this column being filled in: `A9=""` instead of `E9=0`.

When filling in the first column in your example, I ran into a division by zero, which I fixed now (by reverting the formulas in column J). Can you check again whether everything looks alright now?

> @carlobeltrame can you confirm that using Excel (I tested it using LibreOffice)?

I don't have Excel either, was also working with LibreOffice.

**Comment by wp99cp** [comment]
Now it looks promising 🚀

There is an edge case where the formula triggers `Err:502` if the "Horizontaldistanz" is exacly zero and the elevation is decreasing. See the following example:
image

Neverthless, I think it is save to assume that the "Horizontaldistanz" is never exacly zero, as mathematically speeking this would imply infinit gradient at those points. @maede97 what do you think?

I will test everything using Excel and then merge this PR, thanks again @carlobeltrame!

**Comment by maede97** [comment]
Yay, infinite gradients!!
I think that is fine as is. :-) 
Thank you @carlobeltrame!

**Comment by wp99cp** [comment]
Excel works as well!
I will merge the PR into dev. It can then be tested on https://dev.map.cevi.tools/ and will be released with the next version.

**Review by wp99cp — APPROVED** [review]

**Pull request merged**
