### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by wp99cp**
- [x] test this on windows. d98d4617d34e216c900f3b328abf067cca315445 may introduce a breaking change -> works with WSL and docker

### CODE REVIEW

**Comment by maede97** [comment]
Works on windows.

**Comment by maede97** [comment]
@wp99cp Somehow, cypress fails. Do you know why?

**Comment by wp99cp** [comment]
> @wp99cp Somehow, cypress fails. Do you know why?

Yes, [043cd8e](https://github.com/cevi/automatic_walk-time_tables/pull/139/commits/043cd8ee3e26c881f6340111790a20554a2714a2) should fix it. The problem was that this PR changed the python images with their alpine version. By default, in an Alpine container curl is not installed, but curl is needed for the health check. I've added curl.

**Comment by wp99cp** [comment]
> Maybe do not load github cache for now? (and for testing)

The problem is independent of the cache... I tried it.

But if clean everything (remove all images and reclone the repo), the test fail locally as well. I get the following error on the startup of `automatic_walk-time_tables_awt-swiss-tml-api_1`:

```
Exception in thread Thread-1 (_load_indexes):
Traceback (most recent call last):
  File "/app/app.py", line 32, in _load_indexes
    name_index = NameFinder(force_rebuild=False, reduced=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/swiss_TML_api/name_finding/name_finder.py", line 24, in __init__
    super().__init__(force_rebuild, reduced)
  File "/app/swiss_TML_api/name_finding/name_index.py", line 46, in __init__
    shutil.unpack_archive(output, "./index_cache/")
  File "/usr/local/lib/python3.11/shutil.py", line 1315, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/usr/local/lib/python3.11/shutil.py", line 1238, in _unpack_tarfile
    tarobj = tarfile.open(filename)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tarfile.py", line 1698, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './index_cache/index_cache.tar.xz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app.py", line 36, in _load_indexes
    name_index = NameFinder(force_rebuild=True, reduced=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/swiss_TML_api/name_finding/name_finder.py", line 24, in __init__
    super().__init__(force_rebuild, reduced)
  File "/app/swiss_TML_api/name_finding/name_index.py", line 73, in __init__
    self.__download_resources(url, folder)
  File "/app/swiss_TML_api/name_finding/name_index.py", line 81, in __download_resources
    shutil.unpack_archive(filename=output, extract_dir=destination)
  File "/usr/local/lib/python3.11/shutil.py", line 1315, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/usr/local/lib/python3.11/shutil.py", line 1209, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: ./resources/swissTLM3D_LV95_data_full/swissTLM3D_LV95_raw.zip is not a zip file
Exception ignored in: <function NameFinder.__del__ at 0x7f5e38a03380>
Traceback (most recent call last):
  File "/app/swiss_TML_api/name_finding/name_finder.py", line 30, in __del__
    self.index.close()
    ^^^^^^^^^^
AttributeError: 'NameFinder' object has no attribute 'index'

```

**Comment by wp99cp** [comment]
I can confirm that `dev` is also affected, but the index is still cached at the moment...

**Comment by wp99cp** [comment]
- [ ] we should squash merge this PR

**Review by maede97 — APPROVED** [review]

**Pull request merged**
