### PR TITLE
Feature/add support for kml files

### PR DESCRIPTION
**Pull request by wp99cp**
Add support for KML files from map.geo.admin.ch by calling the profile API to download the missing height data.
Documentation of the profile API can be found https://api3.geo.admin.ch/services/sdiservices.html?highlight=profile#profile

## TODO

- [x] Add support for KML files in the frontend
- [x] Parse the KML file on the backend and query the height data
- [ ] Add Animation for KML files
- [x] End-To-End Test of a KML file

### CODE REVIEW

**Comment by maede97** [comment]
If we decide to later maybe also support other filetypes, I would highly encourage us to implement option 2. :-)
If we only want to support KML, option 1 would be easier.

Overall, I prefer option 2.

**Comment by maede97** [comment]
@wp99cp I have managed to implement height fetching. Can you take a look?
Furthermore, I prefer to first publish this as a subversion and then tackle the animation in the frontend later (since this is only cosmetics). With this, users could use KML files as soon as possible.

**Comment by wp99cp** [comment]
> @wp99cp I have managed to implement height fetching. Can you take a look? Furthermore, I prefer to first publish this as a subversion and then tackle the animation in the frontend later (since this is only cosmetics). With this, users could use KML files as soon as possible.

Thanks for your work! It's a great start, but I've noticed two problems:

- Somewhere in the code the points get cached, i.g. if you export multiple routes via the web interface, the old routes get included into the later exports (e.g. visible on the map).
- Some KML files trigger an exception. I have included one such KML file (generated via maps.geo.admin.ch with the path tool).
  ```
  backend_1       | Traceback (most recent call last):
  backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
  backend_1       |     self.run()
  backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
  backend_1       |     self._target(*self._args, **self._kwargs)
  backend_1       |   File "/app/app.py", line 40, in create_export
  backend_1       |     generator = AutomatedWalkTableGenerator(args, uuid)
  backend_1       |   File "/app/automatic_walk_time_tables/generator.py", line 39, in __init__
  backend_1       |     self.path = parser.parse()
  backend_1       |   File "/app/automatic_walk_time_tables/utils/file_parser.py", line 83, in parse
  backend_1       |     path_lv03 = heightFetcher.fetch_path(path_lv03)
  backend_1       |   File "/app/automatic_walk_time_tables/utils/height_fetcher.py", line 67, in fetch_path
  backend_1       |     raise Exception("Failed to fetch elevation for path")
  backend_1       | Exception: Failed to fetch elevation for path
  ```

[failed_KML.zip](https://github.com/cevi/automatic_walk-time_tables/files/8340636/failed_KML.zip)

**Comment by maede97** [comment]
@wp99cp Fixed, can you double check?

**Comment by wp99cp** [comment]
> @wp99cp Fixed, can you double check?

Thanks for your work. Multiple exports in a row now work without problem. 

But I found a new problem: KML file is attached... Note the file is created using the "Messen" function of [maps.geo.admin.ch](maps.geo.admin.ch).
```
backend_1       | Traceback (most recent call last):
backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
backend_1       |     self.run()
backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
backend_1       |     self._target(*self._args, **self._kwargs)
backend_1       |   File "/app/app.py", line 40, in create_export
backend_1       |     generator = AutomatedWalkTableGenerator(args, uuid)
backend_1       |   File "/app/automatic_walk_time_tables/generator.py", line 39, in __init__
backend_1       |     self.path = parser.parse()
backend_1       |   File "/app/automatic_walk_time_tables/utils/file_parser.py", line 61, in parse
backend_1       |     if not 'LineString' in root[0][1][3].tag:
backend_1       | IndexError: child index out of range
```

On top of that, it seems that GPX files don't work anymore. I now got an error, whereas with version 2.1.0, the live version, it works. The file is also attached.

```
backend_1       | Traceback (most recent call last):
backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
backend_1       |     self.run()
backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
backend_1       |     self._target(*self._args, **self._kwargs)
backend_1       |   File "/app/app.py", line 40, in create_export
backend_1       |     generator = AutomatedWalkTableGenerator(args, uuid)
backend_1       |   File "/app/automatic_walk_time_tables/generator.py", line 36, in __init__
backend_1       |     self.path = parser.parse()
backend_1       |   File "/app/automatic_walk_time_tables/utils/file_parser.py", line 38, in parse
backend_1       |     lv03_path = heightFetcher.fetch_path(lv03_path)
backend_1       |   File "/app/automatic_walk_time_tables/utils/height_fetcher.py", line 67, in fetch_path
backend_1       |     raise Exception("Failed to fetch elevation for path")
backend_1       | Exception: Failed to fetch elevation for path
```

[KML_and_GPX_file.zip](https://github.com/cevi/automatic_walk-time_tables/files/8371331/KML_and_GPX_file.zip)

**Review by wp99cp — COMMENTED** [review]
Everything seems to work (with my test routes)

**Review by maede97 — CHANGES_REQUESTED** [review]
I think it looks good for now.

Things to do: 
- Decide on a version number (2.2.0 or 3.0.0). Probably 2.2.0, since not all features are currently fully supported (like animation for KML files. If all these are done, we could probably move to the third version?)
- I have also opened issue #62, which tracks the work on adding the animation.

@wp99cp Can you fix the merge conflict in the `package-lock.json` and also bump the version number to your liking? Afterwards, I think you can merge :-)

**Comment by wp99cp** [comment]
> * Decide on a version number (2.2.0 or 3.0.0). Probably 2.2.0, since not all features are currently fully supported (like animation for KML files. If all these are done, we could probably move to the third version?)

I think we should go for 2.2.0, considering your arguments.

**Review by maede97 — APPROVED** [review]

**Pull request merged**
