### PR TITLE
Improve Usability on Small Screens

### PR DESCRIPTION
**Pull request by wp99cp**
This PR tries to improve the layout on small screens. It's still _work in progress_, see the discussion in #181

# TODO
- [x] Try to implement #182 (optional)
- [x] Bump version Number (compulsory)
- [x] Fix Unit Tests (compulsory)

## Side-Note
I had to rebase the dev branch to keep our git history clean (we once squashed merged from dev without rebasing it...) Sorry for the inconvenience. @maede97 and @carlobeltrame make sure to update your dev branch by running `git reset --hard origin/master`

### CODE REVIEW

**Comment by maede97** [comment]
Looks pretty good already!

This (image) is the current frontpage from my mobile. I think it is unclear that you can move the bar upwards. Can we make the lower part span half screen? Scrolling just moves the lower 1cm, but keeps the rest of the map ontop.

**Comment by wp99cp** [comment]
> Looks pretty good already!
> 
> This (image) is the current frontpage from my mobile. I think it is unclear that you can move the bar upwards. Can we make the lower part span half screen? Scrolling just moves the lower 1cm, but keeps the rest of the map ontop.

Thank you for your feedback. I have made adjustments to increase the touch area for easier resizing of the bottom bar. Could you test it out and let me know if it feels more intuitive to use?

Another alternative would be to make the lower part span half of the screen (as you suggested), but this would be a more complex process as the maps would need to be enlarged rather than simply overlayed, with that I had some issues...

**Comment by maede97** [comment]
Maybe we can also ditch the map on mobile? Or make it scrollable --> if you scroll down, the map fades upwards while the content fades in?

**Review by maede97 — APPROVED** [review]
I see that it is not so easy otherwise. Let's use this for now (we can always come back again if time allows it...)

**Comment by maede97** [comment]
@wp99cp I leave squast & merge to you.

**Comment by maede97** [comment]
Maybe we can also include https://github.com/cevi/automatic_walk-time_tables/pull/186 and https://github.com/cevi/automatic_walk-time_tables/pull/187 in the same release?

**Pull request merged**
